In [2]:
import numpy as np
import pandas as pd

In [43]:
# create single dimension array using numpy
a = np.array([1,2,3,4,5])
a[3]

4

In [44]:
# create array of rank 2
array = [[1,2,3],[4,5,6]]
b = np.array(array)
b[1][1]

5

In [45]:
# create numpy array from tuple
tup = ((1,2,3),(4,5,6))
c = np.array(tup)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# array slicing
arr = np.array([[1,2,3,4,5,6],
    [-1,4,7,-3,9,0],
    [3,-8,4,-2,0,8]])
print("original array:")
print(arr)
arr1 = arr[:3,::2]
print("arr1:")
print(arr1)

original array:
[[ 1  2  3  4  5  6]
 [-1  4  7 -3  9  0]
 [ 3 -8  4 -2  0  8]]
arr1:
[[ 1  3  5]
 [-1  7  9]
 [ 3  4  0]]


In [47]:
# operations on arrays
arr1 = np.array([[1,2,3],[4,5,6]])
print("adding each element with scalar value:\n", arr1 + 3)
arr2 = np.array([[9,6,3],[8,6,4]])
print("======================")
print("subtracting scalar value from arr2: \n", arr2 - 2)


adding each element with scalar value:
 [[4 5 6]
 [7 8 9]]
subtracting scalar value from arr2: 
 [[7 4 1]
 [6 4 2]]


In [48]:
#sum of individual array elements
# arr1 = np.array([[1,2,3],[4,5,6]])
# arr1.sum()

# addition of two arrays
arr1 = np.array([[1,2,7],[4,5,2]])
arr2 = np.array([[3,8],[4,6]])
sum_arr = arr1 + arr2
sum_arr

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
# in built method to find the size and shape of the array
arr1 = np.array([[1,2,7],[4,5,2]], dtype=float)
# arr1.shape
# datatype of an array element
# arr1.dtype
# arr1.size
arr1.ndim

2

1. Write a python script using numpy to create 2X2 array from a 3X3 array
2. Consider two arrays of size (2,3). Multiple each element of array1 with 5 and subtract array2 with array1

In [ ]:
arr = np.array([[1,2,3],[4,6,9],[2,5,9]])
slice_arr = arr[:2, ::2]
slice_arr

array([[1, 3],
       [4, 9]])

In [49]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[9,8,7],[6,5,8]])

array_mul = array1 * 5
print("multiplied array :", array_mul)

array_sub = array2 - array_mul
print("subtracrted array", array_sub)


multiplied array : [[ 5 10 15]
 [20 25 30]]
subtracrted array [[  4  -2  -8]
 [-14 -20 -22]]


In [28]:
# numpy in built methods
# np.zeros
arr = np.zeros((3,8))
# np.full
arr1 = np.full((3,2), 4, dtype=complex)
# np.arange
arr2 = np.arange(0, 100, 25)
#np.linspace
arr3 = np.linspace(0,10,5)
# np.reshape
arr4 = np.array([[1,2,3,4],[5,6,7,8],[1,4,6,9]])
arr4.reshape(2,3,2)
# random
arr5 = np.random.random((3,2))
# flatten
arr6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr7 = arr6.flatten()


9

In [32]:
arr = np.array([[1,2,3],
                [1,5,7],
                [8,5,3]])
arr_max = arr.max(axis=1) # 1 = row wise maximum, 0 = column wise maximum
arr_min = arr.min(axis=0) # 1 = row wise minimum, 0 = column wise minimum
cumulative_sum = arr.cumsum(axis=1)
cumulative_sum


array([[ 1,  3,  6],
       [ 1,  6, 13],
       [ 8, 13, 16]])

In [39]:
# sort
arr = np.array([[12,3,6],
                [11,4,56],
                [82,55,33]])
np.sort(arr,axis=0)

array([[11,  3,  6],
       [12,  4, 33],
       [82, 55, 56]])

In [12]:
import pandas as pd
import numpy as np

In [45]:
a = np.array([1,2,3,4,5])
series = pd.Series(a)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [53]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr)

arr_list = [[23.89, "world", np.nan, "pandas", np.inf, 3+4j, "good"], [1,2,3,4,5]]
df2 = pd.DataFrame(arr_list)
df2

0      1    2       3    4         5     6
0  23.89  world  NaN  pandas  inf  3.0+4.0j  good
1   1.00      2  3.0       4  5.0 N000a000N  None

In [57]:
fruits = {"apples": [3,4,5,7],
          "oranges": [4,3,6,8],
          "grapes": [5,8,1,2]
          }

df_fruits = pd.DataFrame(fruits, index=["John", "Andy", "Paddy", "Jeff"])
df_fruits

apples  oranges  grapes
John        3        4       5
Andy        4        3       8
Paddy       5        6       1
Jeff        7        8       2

In [9]:
df = pd.read_csv("USA_Housing.csv")
df.describe()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
count       5000.000000          5000.000000                5000.000000   
mean       68583.108984             5.977222                   6.987792   
std        10657.991214             0.991456                   1.005833   
min        17796.631190             2.644304                   3.236194   
25%        61480.562388             5.322283                   6.299250   
50%        68804.286404             5.970429                   7.002902   
75%        75783.338666             6.650808                   7.665871   
max       107701.748378             9.519088                  10.759588   

       Avg. Area Number of Bedrooms  Area Population         Price  
count                   5000.000000      5000.000000  5.000000e+03  
mean                       3.981330     36163.516039  1.232073e+06  
std                        1.234137      9925.650114  3.531176e+05  
min                        2.000000       172.610686  1.593866e+04  
25%                        3.140000     29403.928702  9.975771e+05  
50%                        4.050000     36199.406689  1.232669e+06  
75%                        4.490000     42861.290769  1.471210e+06  
max                        6.500000     69621.713378  2.469066e+06

In [21]:
fruits = {"apples": [3,4,5,7],
          "oranges": [4,3,np.nan,8],
          "grapes": [5,np.nan,6,2]
          }

df_fruits = pd.DataFrame(fruits, index=["John", "Andy", "Paddy", "Jeff"])
print(df_fruits)
# print("before fillna:\n",df_fruits)
# afnadf = df_fruits.fillna(89)
# print("after fillna:\n", afnadf)
df_fruits.dropna(axis=1)
df_fruits.

       apples  oranges  grapes
John        3      4.0     5.0
Andy        4      3.0     NaN
Paddy       5      NaN     6.0
Jeff        7      8.0     2.0


apples
John        3
Andy        4
Paddy       5
Jeff        7

In [15]:
# !pip install matplotlib

## jupyter notebook --generate-config ##

import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame({
    'Name': ['John', 'Sammy', 'Joe'],
    'Age': [45, 38, 90]
})
df.plot(x="Name", y="Age", kind="bar")
###########################################
df = pd.DataFrame({
    'Age': [45, 38, 90, 60, 40, 50, 2, 32, 8, 15, 27, 69, 73, 55]
})
print(df)
plt.hist(df["Age"])
plt.show()
###########################################
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
                               'Mahindra', 'Maruti', 'Hyundai',
                               'Renault', 'Tata', 'Maruti'],
                     'Year': [2012, 2014, 2011, 2015, 2012,
                              2016, 2014, 2018, 2019],
                     'Kms Driven': [50000, 30000, 60000,
                                    25000, 10000, 46000,
                                    31000, 15000, 12000],
                     'City': ['Gurgaon', 'Delhi', 'Mumbai',
                              'Delhi', 'Mumbai', 'Delhi',
                              'Mumbai', 'Chennai',  'Ghaziabad'],
                     'Mileage':  [28, 27, 25, 26, 28,
                                  29, 24, 21, 24]})
display(data)
display(data.loc[(data.Year==2012)])
###########################################
display(data.iloc[[0, 2, 4, 7]])
display(data.iloc[1: 5, 2: 5])



Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
2    Tata  2011       60000   Mumbai       25
4  Maruti  2012       10000   Mumbai       28
7    Tata  2018       15000  Chennai       21

Kms Driven    City  Mileage
1       30000   Delhi       27
2       60000  Mumbai       25
3       25000   Delhi       26
4       10000  Mumbai       28